services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 7777:7777
    depends_on:
      database:
        condition: service_healthy
      flyway:
        condition: service_started
    env_file:
      - .env
  database:
    container_name: "postgres-database"
    image: "postgres:13.4"
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 5s
      timeout: 3s
      retries: 5
  flyway:
    image: flyway/flyway:7.3.0-alpine
    environment:
      - FLYWAY_USER=username
      - FLYWAY_PASSWORD=password
      - FLYWAY_URL=jdbc:postgresql://postgres-database:5432/database
    depends_on:
      database:
          condition: service_healthy
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate